Update mongo.yaml

diff --git a/.github/workflows/mongo.yaml b/.github/workflows/mongo.yaml
--- a/.github/workflows/mongo.yaml
+++ b/.github/workflows/mongo.yaml
@@ -29,10 +29,13 @@ jobs:
         run: bash ./install_mongodb.sh --auto-create | tee /tmp/mongodb-install.log
 
       - name: Verify MongoDB service
+        run: systemctl is-active mongod || (echo "MongoDB failed to start" && exit 1)
+
+      - name: Extract MongoDB Credentials and Save to File
         run: |
-          #grep 'MongoDB username:' /tmp/mongodb-install.log | awk '{print $3}' > /tmp/mongodb-user.txt
-          #grep 'MongoDB password:' /tmp/mongodb-install.log | awk '{print $3}' > /tmp/mongodb-pass.txt
-          systemctl is-active mongod || (echo "MongoDB failed to start" && exit 1)
+          grep 'MongoDB username:' /tmp/mongodb-install.log | awk '{print $3}' > /tmp/mongodb-user.txt
+          grep 'MongoDB password:' /tmp/mongodb-install.log | awk '{print $3}' > /tmp/mongodb-pass.txt
+
 
       - name: Test MongoDB authentication
         run: |
